### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by ghost** [FoxUSA/OpenNote#107]
Hi,
i have installed OpenNote to my webspace at uberspace.de and i can open the startpage. 
First thing i do was to register a new user. After that i checked the database. The newe user is in. Now i try to login with the new user. I get the message "Credentials accepted". But i was redirtected to the screen with the two buttons Login/Register. I dont know why its happening... what do i wrong? The login is okay but its dont redirect me to the edit page...

Thanks for your help

**Comment by simonpostma** [comment]
I am currently experiencing this issue, are there any known fixes?
