### ISSUE TITLE
Can I ask a question here? Login screen stuck on loop?

### ISSUE THREAD

**Issue by bushrang3r** [FoxUSA/OpenNote#115]
I just found this great project today and have installed it on my server. 
When I try to log in, I get the message that the credentials have been accepted but then the login screen reloads and I never get any further than that.

**Comment by aprather51** [comment]
I am facing same issues here.

**Comment by FoxUSA** [comment]
@bushrang3r @aprather51 ,
What browser are you using? does it work on the demo site?

**Comment by bushrang3r** [comment]
Hi FoxUSA, 
I was using Seamonkey (basically Firefox I think?).
After I saw your question asking which browser I'm using, I tried Opera and I can login with that although I get no wysiwyg controls when writing a note. 
So here's what I've got.
Seamonkey - my own instance - reloads the Login/Register screen after login attempt
Seamonkey - demo site - 100% OK.
Opera - my own instance - Login successful - no wysiwyg controls 
Opera - demo site - Login successful - no wysiwyg controls

Thanks :)

**Comment by FoxUSA** [comment]
@bushrang3r can you press F12 and see if a console error is being thrown on your instance? Or post your instance url it here.

**Comment by bushrang3r** [comment]
http://kunrig.org/OpenNote

**Comment by FoxUSA** [comment]
@bushrang3r It appears to be setup correctly. I can log in with chrome, and SeaMonkey and it worked.
Can you try again?

**Comment by bushrang3r** [comment]
Thanks for checking :)
I tried again and I still get the loop as I described earlier.
I also disabled all browser add-ons/extensions but same result.
Also tried making a new user on my system but same results for both Seamonkey and Opera as above.
Were you able to do wysiwyg editing in both browsers on my instance?

**Comment by FoxUSA** [comment]
I was. I am using Seamonkey 2.32

**Comment by FoxUSA** [comment]
@bushrang3r, How did you download? What timezone are you in? this sounds familiar.

**Comment by FoxUSA** [comment]
Try pulling this fix if you do not already have it https://github.com/FoxUSA/OpenNote/commit/c8916ea54a6f77fa2285428c573dc7c88e7d4bed

**Comment by bushrang3r** [comment]
Excellent!!! Thank you sir! That fixed the issue. I can now login and use wysiwyg controls :)
My timezone is JST (Japan Standard Time) UTC/GMT +9 hours
I downloaded it from here > https://github.com/FoxUSA/OpenNote/releases
using the OpenNote.zip button and then ftp'd to my server.
Thanks again!

**Comment by bushrang3r** [comment]
Oops, I still have the problem of no wysiwyg toolbar nor note field when using Opera. It's working fine in Seamonkey and that's my main browser so I'm happy with that but just to let you know anyway....

**Comment by FoxUSA** [comment]
@bushrang3r are you using the latest Opera version?

**Comment by bushrang3r** [comment]
No! I just found out that the version I'm using is quite old. 12.16. Sorry, I'll do something about it.

**Comment by cavebeat** [comment]
hi, 
i am having same issue with Login Loop

latest opennote release 14.07.02
FireFox 35.0

i am able to do things, as long as the "Credentials Accepted" Toaster is available in the right bottom corner. 

Edit is always possible, and save too. but selecting folder or creating a note always requires a login again.

**Comment by FoxUSA** [comment]
@cavebeat pull this fix https://github.com/FoxUSA/OpenNote/commit/c8916ea54a6f77fa2285428c573dc7c88e7d4bed

**Comment by jniggemann** [comment]
I have the same issue using version 14.07.02 with FF 35.0.1. Installation was OK, but I can't register or log in. The "users" table in sqlite is empty and nothing is logged to the browsers' console. Fix c8916ea doesn't change that.

**Comment by jniggemann** [comment]
Update: I also tried this with a MySQL DB and the error persists, regardless of patch c8916ea being installed or not.

**Comment by jniggemann** [comment]
@FoxUSA Do we have to install [OpenNoteService-PHP](https://github.com/FoxUSA/OpenNoteService-PHP) in order to use OpenNote?

**Comment by FoxUSA** [comment]
@jniggemann No, https://github.com/FoxUSA/OpenNoteService-PHP is the github project for the backend. Maybe someday we will have more than one. For now, it is included in all binary downloads and in docker scripts.

**Comment by jniggemann** [comment]
Go it working:
* Make change as described in #120 plus a similar change in Config.template
* call Service/install.php, select sqlite --> white screen, reload -> "successful" message
* register (this still works in any browser)
* login (does not work with FF35, I only had success using Chromium V42.0.2273.0)

**Comment by FoxUSA** [comment]
@jniggemann 
Glad to hear it.

**Comment by QkiZMR** [comment]
Firefox 37.0 and I ran in login loop. After enter creds I got 'Credentials Accepted' notification but I'm still on Login | Register buttons.
