### ISSUE TITLE
can't register after installation

### ISSUE THREAD

**Issue by jniggemann** [FoxUSA/OpenNote#116]
Hi, this looks exactly like the piece of software I was looking for.
I just installed OpenNote on RedHat with MySQL, but I can't register.
There's nothing in the error log, and the table 'users' is also empty, the error message 'Invalid credentials' is displayed.

Did I miss something?

**Comment by FoxUSA** [comment]
If you press f12 in your browser can you see what error is being thrown?
Normally this means the front end cannot communicate with the API.

**Comment by arktyk** [comment]
@jniggemann Did you ever resolve this issue?  I believe I might be having the same one, but was unsure and filed a separate bug, [#119](https://github.com/FoxUSA/OpenNote/issues/119), if you were able to solve the problem, I would appreciate it if you could let me know how you did so.  Thank you.

**Comment by jniggemann** [comment]
@arktyk I never resolved this and worse, I can't debug this as there's nothing logged to the browsers console... I'd so like to try OpenNote, but I can't get it to run on any of the machines I tested with (RedHat, Bodhi, Debian).

**Comment by jniggemann** [comment]
FWIW, this issue and #119 both seem to be duplicates of #115 ...

**Comment by TheOtterslider** [comment]
I just downloaded and installed today.  I think I'm having the same issue.

**Comment by FoxUSA** [comment]
@TheOtterslider Can you see if an error is being thrown.
What version of php are you using on what version of mysql
Do you have the case in-sensative  option turned on?

**Comment by TheOtterslider** [comment]
Error shown in the interface - invalid credentials (slides in from the lower right).  Nothing else appears when I hit f12
Apache/2.2.15
PHP/5.6.6
Mysql 5.1.73
Nothing else shown in Apache error logs

**Comment by FoxUSA** [comment]
@TheOtterslider Do you have the case in-sensative option turned on?

https://dev.mysql.com/doc/refman/5.0/en/identifier-case-sensitivity.html

What operating system?

**Comment by TheOtterslider** [comment]
Cent OS 6.6
I installed the default version/config from yum.  How can I determine if the option for case sensitivity is set?  I can't find anything online that says something like "run this command" or "check this file"  I'm not a mysql admin so any pointers in that direction would be really helpful

**Comment by FoxUSA** [comment]
Run
```
SELECT @@GLOBAL.lower_case_table_names
```
 on your server

**Comment by TheOtterslider** [comment]
mysql> SELECT @@GLOBAL.lower_case_table_names;
+---------------------------------+
| @@GLOBAL.lower_case_table_names |
+---------------------------------+
|                               0 |

**Comment by FoxUSA** [comment]
@TheOtterslider 
ya you have case sensative table names. Set that to a 1. It shouldn't break any of your existing apps.

**Comment by jniggemann** [comment]
Why is this issue closed when there's no solution? I still can't login on a fresh install when using sqlite...

**Comment by TheOtterslider** [comment]
Just an update...I updated GLOBAL.lower_case_table_names to 1, bounced mysqld, verified the change, and am still having problems registering.

**Comment by FoxUSA** [comment]
@jniggemann @TheOtterslider,
In the next version mysql is optional.

@TheOtterslider try dropping the DB and rerun the install

**Comment by TheOtterslider** [comment]
>try dropping the DB and rerun the install
Same error.  

>In the next version mysql is optional.
You mean another DB is used?  What's the datastore?

**Comment by Hugao** [comment]
I'm having the same problem, I can't register on my local instance but on the demo I can.
I'm using sqlite
My system:
Apache 2.4.12
PHP 5.6.9
Firefox 38.0.1
Chromium 43.0.2357.65

**Comment by FoxUSA** [comment]
@TheOtterslider Next version uses couchdb and pouchdb to enable offline access and data sync. At the moment, mysql is only used if you want to upload fles.

**Comment by FoxUSA** [comment]
@Hugao Are you on windows?

**Comment by Hugao** [comment]
@FoxUSA  I'm on Arch Linux

**Comment by FoxUSA** [comment]
@Hugao have you pulled this fix https://github.com/FoxUSA/OpenNote/commit/c8916ea54a6f77fa2285428c573dc7c88e7d4bed .
Also when registering does it create a user in the mysql users table?

**Comment by Hugao** [comment]
@FoxUSA I'm using sqlite, and no user is created

**Comment by FoxUSA** [comment]
@Hugao can you make sure the config.php points to the correct sqllite database

**Comment by Hugao** [comment]
@FoxUSA it points to the correct path, I double checked

**Comment by FoxUSA** [comment]
@Hugao You may want to download a copy of my working branch. I dont have a lot of documentation yet but the code is feature complete.

Basically you can use it at just an html5 app with manual backup and restore. Or you can install a CouchDB server and sync with it.

Only issues I am having is with file upload(Still requires a php based api).
As well as issues with offline apps using self signed ssl keys.

**Comment by b3nm0n** [comment]
I have this same problem.  Nothing I do changes this error. Ran Firebug and got the following:

POST http://localhost/OpenNote/Service/service.php/user/maint&maint 500 Internal Server Error 17ms

Looking further, I get 

angular.min.js (line 78)

I am not a coder, I am a Sys Admin with some xtra skills. This is a local install on Fedora 21, fully updated..

**Comment by FoxUSA** [comment]
@b3nm0n In a browser window go to `http://localhost/OpenNote/Service/service.php/user/maint&maint` what does the body say?

**Comment by b3nm0n** [comment]
I get the following: 

Invalid username

However the username is in the database, it is spelt correctly, etc.  I have tried to create a new user and get the same result.

**Comment by FoxUSA** [comment]
See new version

**Comment by abalage** [comment]
It does not look good. After upgrading to new version I cannot even see the login form.
On "#/settings/legacy/" I can register a user as many times I want (checked in mysql table users). I could import my legacy stuff but it is accessible to everyone.

**Comment by FoxUSA** [comment]
No its not. This is a html5 app. Its now cached locally on your browser. In chrome you can have multiple profiles which can hide your notes.

**Comment by abalage** [comment]
> Its now cached locally on your browser
I think I am missing something. I still have my notes in mysql table 'notes'.
What is it good for to leave them up to my browser's cache? I would like to access them from any other location. 

In upgrade guide I see this.
> There have been major changes in this release. You will need to follow the CouchDB instructions in the Install documentation.

In install guide.
> If you want sync your notes with a server, you will need to install CouchDB
So, does it mean, MySQL is not supported anymore and everyone should migrate to CouchDB?

Will I have a login form again if I follow the CouchDB install guides?

**Comment by FoxUSA** [comment]
@abalage Correct. Mysql is no longer supported**** and is going away. CouchDB makes it easier to allow offline note sync.
The notes are still in the mysql table notes because you have to migrate them.


**** Still used for file uploads at this time.
