### ISSUE TITLE
User name is available when registering, but password entry gives "Invalid Credentials"

### ISSUE THREAD

**Issue by arktyk** [FoxUSA/OpenNote#119]
Hello,
I was able to install OpenNote with MySQL.  When I register and enter the username, the application changes from "Username must be at least four characters" to "Available" after the fourth character, but when I attempt to enter the password and click Register, I get "Invalid Credentials."  Any help would be greatly appreciated.  Thank you.

**Comment by arktyk** [comment]
It is returning a HTTP/1.1 500 Internal Server Error whenever I try to register.  If anyone can provide help, I would appreciate it.  Thank you.

**Comment by FoxUSA** [comment]
Please see https://github.com/FoxUSA/OpenNote/issues/115
