### ISSUE TITLE
Disable Register button

### ISSUE THREAD

**Issue by askans** [FoxUSA/OpenNote#121]
Thank you very much for this nice piece of web service. I was able to install and use it. But I want to use it for myself only. Therefore nobody else should be able to register to my installation. How do I disable the registration button, so nobody else but me can use it?

**Comment by FoxUSA** [comment]
Change this to return false
https://github.com/FoxUSA/OpenNoteService-PHP/blob/master/Service/Config.php#L68

**Comment by askans** [comment]
Thanks for the help. Line 83 has to be set to false instead of 68. The registration button will still be available but registration is not successful
