### ISSUE TITLE
Importing data from [insert note app here]?

### ISSUE THREAD

**Issue by Snowflake6** [FoxUSA/OpenNote#127]
Is there any plans for migration assistance, to get notes out of, for example, Evernote and into OpenNote?  I didn't see an enhancement request for this yet, maybe that's something that can be looked at?

**Comment by FoxUSA** [comment]
Maybe. I wrote a converter for OneNote. It was really complicated to run so I never released it. Next version(Sitting in my working branch till I get around to write upgrade documentation) will let you import a json file
