### ISSUE TITLE
Move notes

### ISSUE THREAD

**Issue by blutril** [FoxUSA/OpenNote#128]
Will there be a feature to move notes into different folders? at the moment the only method to move a note i see is to copy the content and create a new one in the related folder.

**Comment by FoxUSA** [comment]
@blutril yes,
I had this, then I switched drag and drop plugins and lost the ability.
The only thing holding this feature back is the UI for it. If you have any suggestions, I am all ears.

**Comment by FoxUSA** [comment]
@blutril Better late then never. I have added the ability to cut and paste a note into folders
