### ISSUE TITLE
QuotaExceededError: Dom exception 22

### ISSUE THREAD

**Issue by rosoft2001** [FoxUSA/OpenNote#129]
On iPad Safari private browsing: after username/password click login.

I found sometrhing related here: http://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st

Work in iPad Chrome private browser...

Also touching the blue square don't open the note in both browsers.

**Comment by FoxUSA** [comment]
You have to allow local storage.
