### ISSUE TITLE
Not connecting to DB

### ISSUE THREAD

**Issue by SpudR** [FoxUSA/OpenNote#134]
Hi Jacob
I've not managed to upgrade my system to the latest release.
Overwriting the files on an existing install made it not possible to edit or create new notes. 
Creating a new install and a whole new DB and the new install made no reference to the DB at all (nothing written to any of the tables)
I have followed both the upgrade docs and the new install docs but the new version simply doesn't work for me :(

Any idea?

**Comment by FoxUSA** [comment]
@SpudR The edit and create endpoints were hidden on purpose. You need to install CouchDB. It a nosql database server that allows the html5 client to have a full offline copy of your notes. So say when your in a store needing to look at your grocery list you will have the full notebook cached.

**Comment by SpudR** [comment]
Thanks for the update, but I've got this running on a shared web server, with no way to install another db.
So is this killed for me?

**Comment by FoxUSA** [comment]
You can revert. Just download the older version and overwrite everything except the configs and the upload directory. Should still work ok.
