### ISSUE TITLE
CouchDB "option"

### ISSUE THREAD

**Issue by slars** [FoxUSA/OpenNote#135]
The 15.07 release states that CouchDB is now an option for offline use, but it doesn't appear that there is any way to use this release without integrating CouchDB.  Am I mistaken? I want to use some of the new features in v15, but I don't want to mess with the offline/CouchDB option.  After several hours (most of which were frustrating!) I reverted back to v14.  (And I have to say the floating reminder in the corner is quite annoying.)

slars

**Comment by FoxUSA** [comment]
There are not really any new features in the latest release other than the offline html5 app.
You can use the app with just localstorage if you dont want to use CouchDB.
