### ISSUE TITLE
Can not register on a new fresh install.

### ISSUE THREAD

**Issue by Jherring01** [FoxUSA/OpenNote#142]
I have just performed a fresh install, and I get the setup to come up nicely, it just doesn't allow me to register and login. Straight to notes. Latest version, MySql installation.

**Comment by FoxUSA** [comment]
New app is a offline html5 app that uses local storage. The mysql option is the last version and is no longer actively supported. If you need to import your old notes you can do so in the settings. We are using CouchDB for data persistence.
