### ISSUE TITLE
User login? / LDAP etc...

### ISSUE THREAD

**Issue by api984** [FoxUSA/OpenNote#143]
Hello,

Can we add LDAP or etc so opennote is not Allow All to read and write once
installed?

I can only add .htaccess for now to protect notes?

thanks.

**Comment by api984** [comment]
got it. register does not seem to have an effect...

**Comment by FoxUSA** [comment]
OpenNote is a html5 app. Its not read all. You can persist your notes in a couchdb database.
The register you are refering to is for the legacy API and for file upload.
