### ISSUE TITLE
No login required for usage? 

### ISSUE THREAD

**Issue by metzbernhard** [FoxUSA/OpenNote#145]
I just hosted opennote on my homeserver using the first way in the install.md, so just extracting the latest build in a folder and opening the URL/opennote and got instantly unto the opennote screen and was able to make new notes, edit old ones etc.  
The HowToUse.md indicates that the services uses a login, but I seem not be able to activate this, from what I read in the install.md it's not the File/Legacy Service Login Screen. 

Am I missunderstanding something horribly or is the service meant to be usable completely without login? 

Thank you in advance.

**Comment by FoxUSA** [comment]
@metzbernhard ,
This is a offline HTML app. It persists data in your browsers storage.
You can sync it to a CouchDB server with a username and password.

Think of it more like MS Word rather than a traditional webpage.

I do this so you can access the app offline on your smart phone as if it was a native app.

**Comment by jaguaaaar** [comment]
I'm sorry but I still not understand. in the install :

> Manual
> MYSql
> 
>     Create a MYSQL database named "OpenNote"
>     Download and extract OpenNote into a folder on your php web-server called "OpenNote"
>     Open up the Service/model/sql folder and run notebook.sql in your OpenNote database
>     Change the database connection settings inside of Service/Config.php to match your db settings. These are stored in the following lines of code in /OpenNote/Config.php:
> 
>     $dbUserName = "notebook";
>     $dbPassword = "password";
>     $dbServer = "127.0.0.1";
>     $dbName = "notebook";
> 
>     Now the site install is complete. You can now open the site by going to your webserver url +/OpenNote
> 
In my case, i filled up with my mysql base, but there is no synchronization, my sql database stay empty, and I don't understand why...
Any idea, or the is something else I didn't understand?
Thanks

**Comment by FoxUSA** [comment]
That part does require an install. Its in the settings for the app. The mysql based part is for file uploads.
