### ISSUE TITLE
Unable to Setup on CentOS 7.2

### ISSUE THREAD

**Issue by LOTRg** [FoxUSA/OpenNote#146]
I have been trying to set this up for a week now and I am unable to setup on CentOS 7.2. is there a a guide ( step by Step ) for Javascript newbies like myself to follow ?

**Comment by LOTRg** [comment]
This have been resolved using the older version 14.07.02.

**Comment by LOTRg** [comment]
this have been resolved using older version 14.07.02. As stated by @FoxUSA in his comment on issue #145 https://github.com/FoxUSA/OpenNote/issues/145, the current version is an offline app not designed for webservers natively unless using other mechanism.

**Comment by FoxUSA** [comment]
@LOTRg is is design to be distributed via a web server. All you do is upload the OpenNote directory that way you can access the files
