### ISSUE TITLE
Issues with version 14.07.02

### ISSUE THREAD

**Issue by LOTRg** [FoxUSA/OpenNote#147]
Great app and exactly what I need. However some issues were encountered.
Since the latest version 15.xx is an offline app, the latest webserver version is 14.07.02 which comes with a few issues, hoping they could be easily fixed.
1-) if a Note is saved and then try to delete it immediately after save the page freezes, the same applies for editing, workaround : Refresh the browser then do either task.
2-) Registration fails on this version for whatever reason. workaround : use version 15.xx just to create the users from the Legacy page settings then switch back to version 14.07.02 and the logins would work.
3-) Application prompts for update always to version 15.xx which is not compatible with Webserver setup : workaround : open OpenNote/openNote/openNote.js file and comment out the update function to look like this :
        //Check for updates
                //$http.get(config.getUpdateURL()).then(
                //      function(response){//Successful
                //              if(response.data.version!=config.getVersion())
                //                      alertify.log("<a href='"+response.data.updateURL+"' target='_blank'>"+response.data.updateText+"</a>", "", 0);
                //      });

Hope the developer can have sometime to look at these issues.

**Comment by FoxUSA** [comment]
15.x.x is an offline app and is the only supported version. You can use couchdb to syn and persist notes.
