### ISSUE TITLE
Break everything and migrate to using flat key system like s3

### ISSUE THREAD

**Issue by FoxUSA** [FoxUSA/OpenNote#148]
This will allow better search results and more awesomeness

**Comment by millette** [comment]
Hi, I just found out about this project. Do you mean to abandon couchdb/pouchdb?

And since you're about self-hosting, you probably don't mean the Amazon service itself, correct?

**Comment by FoxUSA** [comment]
@millette There is an issue with search result being useless. My though is in couchdb use a s3 like key instead of guids

**Comment by millette** [comment]
Ok :-) Not sure what that means, I never used s3. Thanks for the clarification.
