### ISSUE TITLE
Can't login after install.

### ISSUE THREAD

**Issue by loifarn** [FoxUSA/OpenNote#151]
Install finished seemingly successfully, but I now get "Connection to Service failed" and "Invalid crendtials" when I'm trying to log in.

I'm using nginx through Ajenti-V.

Any help would be greatly appriciated.
nginx config 

> server {
>     listen *:80;
>     
>     
>     server_name note.loif.no;
> 
>     access_log /var/log/nginx/opennote.access.log;
>     error_log /var/log/nginx/opennote.error.log;
> 
>     root /srv/OpenNote;
>     index index.html index.htm index.php;
> 
>     
> 
>     
>     
>     location ~ [^/]\.php(/|$) {
>         
>         
>         
>         fastcgi_index index.php;
>         include fcgi.conf;
>         fastcgi_pass unix:/var/run/ajenti-v-php-fcgi-opennote-php-fcgi-0.sock;
>         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
> 
>     }
> 
> }

**Comment by FoxUSA** [comment]
@loifarn can you see the webapp at all?

**Comment by FoxUSA** [comment]
Never responded. Closing
