### ISSUE TITLE
How Exactly Do You Upload Files?

### ISSUE THREAD

**Issue by rammjet** [FoxUSA/OpenNote#161]
It has been a solid two days installing and debugging.  I have OpenNote working with CouchDB on Raspberry Pi/Nginx.  I installed MariaDB and used the manual setup.  And after  a few tries, that seems to be accepted.

I have created test notes with images and formatting.

Now I want to test out uploading files.  What kinds of files.  How they are accessible in notes, etc.

But I can't find a description of how to make the upload.

Could you please tell me?

**Comment by rammjet** [comment]
OK, I think I found it.  Clicking the button to create a link or the button to add an image each have upload sections.  And so does the Flash button.  Since when I drag an image into the note it gets displayed, I sort of expected that dragging in a miscellaneous file which is not recognized would trigger some dialog box suggesting ways to deal with it.

Along those lines, is there an easy way to display something like a PDF as an icon that when it is clicked, the contents of the PDF are displayed, and then allow collapsing it back to an icon?

**Comment by FoxUSA** [comment]
@rammjet CKEditor may have a plugin you can use. There is a paid drag and drop plugin I personally use but it is not opensource and has a fee.
