### ISSUE TITLE
I can't install opennote on ubuntu14.04LTS

### ISSUE THREAD

**Issue by kuma1416** [FoxUSA/OpenNote#166]
Hi,
I can't install opennote 15.07.00 on ubuntu 14.04LTS.

I completed to install opennote(reference from https://github.com/FoxUSA/OpenNote/blob/master/Doc/Install.md. but not installed couchDB), I access to http://[Ip address]/opennote/.
I can look opennote on browser, but can't share note between pc.
And can't create account. (I pushed register button, but no changed screen)

Please tell me how to install.

**Comment by FoxUSA** [comment]
You need couchdb

**Comment by FoxUSA** [comment]
The legacy service is only used for uploading images and files
