### ISSUE TITLE
Not able to connect to local couchdb instance. Getting SSL protocol error.

### ISSUE THREAD

**Issue by kadaj** [FoxUSA/OpenNote#169]
I have configured couchdb as mentioned in the installation guide. But opennote is not able to connect it. Browser gives `net::ERR_SSL_PROTOCOL_ERR` message in the console. I am on Ubuntu 15.10 and is using couchdb v1.6.0 from the repository. The ssl cert verification is false.

![opennote-couchdb-ssl-error](https://cloud.githubusercontent.com/assets/1277952/20651692/b7fd2a14-b50f-11e6-9be8-254cb5ecc240.png)

**Comment by FoxUSA** [comment]
Use a free valid cert
https://letsencrypt.org/

**Comment by kadaj** [comment]
For using a valid certificate I need a domain right? Is there a way to not give domain cert?

**Comment by FoxUSA** [comment]
I dont have a way of testing this case. If its just local use http.

**Comment by kadaj** [comment]
Should I connect to port 5984 or 6984? I was connecting to 5984. I think that is the problem. Just came to know that the default ssl port for couchdb is 6984 (from your another comment).
