### ISSUE TITLE
Logo for OpenNote

### ISSUE THREAD

**Issue by petrk94** [FoxUSA/OpenNote#173]
Hello, exist a valid logo for OpenNote to present it in the public?

**Comment by FoxUSA** [comment]
@petrk94 
https://github.com/FoxUSA/OpenNote/blob/master/OpenNote/openNote/style/OpenNote.png
there is a SVG somewhere.
If you come up with a better logo let me know

**Comment by FoxUSA** [comment]
Going to close this. If you end need something else pertaining to logos please open another issue and link to this one.

**Comment by petrk94** [comment]
@FoxUSA well, thats just a circle ;) 
I could make a own logo design for that, I will try that when I have time :)

**Comment by petrk94** [comment]
@FoxUSA 
here is my idea, does not look great
![opennote_edited svg](https://cloud.githubusercontent.com/assets/19719052/24397999/3e513d02-13a8-11e7-82f1-2f34745e5d26.png)

Do you have a idea with the colors? maybe a color change could help

**Comment by petrk94** [comment]
I can try to make a onenote logo clone, but just for OpenNote ;) 
What you think about that?
a color wish?

**Comment by FoxUSA** [comment]
I like the blue and green the note and folder cards are.

**Comment by petrk94** [comment]
@FoxUSA currently Im busy, so sorry that I didnt have time, but I dont forgot it ;)
