### ISSUE TITLE
Instruction on using tags

### ISSUE THREAD

**Issue by ivangretsky** [FoxUSA/OpenNote#177]
Good day!

I am trying a demo installation, but cannot figure out, how tags work. There is no docs on this topic. Tried adding #tag both to the note title and body with no success. Please help me out.

**Comment by FoxUSA** [comment]
It goes in the body and you can #hastag away.
I had some problems with hastags in early versions. I may not have pushed the patches out to the demo.

**Comment by ivangretsky** [comment]
Thanks for your reply. Are you planning to update the demo any time soon?

**Comment by FoxUSA** [comment]
Just did
