### ISSUE TITLE
Log In - Privacy - Syncing ??

### ISSUE THREAD

**Issue by j0nr** [FoxUSA/OpenNote#180]
Hello,

i am just trialling this app, and it looks perfect apart from I am lacking in the understanding of the concept of client-side storage, which I believe is what is happening here...

I installed into a folder on my personal server. When I go to the URL I see the app and can make notes. But if I visit from another device, I see a fresh looking instance... also, presumably, any one in the world can "use" my private server's copy of this app. How is this right? Why is it set up this way?

Maybe I am just lacking understanding, but I am hoping for a more traditional "log in, notes are saved on server" approach. Is it possible to achieve this? 

At the very least, by default, I would think being able to access the same notes from any device when going to the same URL is a must!?

Please help me understand how to use this app as it looks great.

Thanks.

**Comment by FoxUSA** [comment]
This is an HTML 5 app. The code runs in your browser. It is setup this way so you can use it offline. The code is cached in your browser using HTML 5 Manifest. A prime example is I have the app on my phone. I was able to make and see notes when I was on a flight with no Wi-Fi.

You can sync your notes to a CouchDB serer. That requires a username and password. You set this up once per device and its acts like a traditional app.
