### ISSUE TITLE
Build doesn't seem to change anything (WAMP64 in Windows 10)

### ISSUE THREAD

**Issue by PDDeane** [FoxUSA/OpenNote#181]
Hey, I just spent a frustrating time trying to get small edits to source code to be reflected on a localhost web service on my machine, and I'm at my wit's end.

Setup: WAMP64 (Apache, Mysql, PHP) on a Windows 10 machine. Installed angular successfully. Installed composer, bower, npm, grunt all successfully.

Then I changed a word in a partials file -- not code, just part of the web page to be displayed, and then went through the whole build procedure several times, apparently successfully; at least npm, grunt/bower, and composer seemed happy enough. Nonetheless, each time, the original text from the partial file is what gets displayed, not the changed file that I ran the build over.

Cleared the browser cache. Cleaned out the pouchdb. Turned off caching on the Apache server, and verified that a straight .html file changed at once when edited after I did that.

None of that seemed to help. If I pulled the web directory for OpenNote out of the www directory and cleared the browser cache, I'd get file not found, but then the moment I put a freshly built copy of the web directory back in, it would display the original text again.

I am at my wit's end here. Advice?

**Comment by PDDeane** [comment]
Well, whaddaya know. No sooner did I post this than I half solved the problem when I finally figured out how to clear the appcache in Chrome.

Now a change I made to one of the partials that is directly loaded by index.html (NavBarPartial.html) is displaying, but a change I made to folderPartial.html, which is indirectly loaded, is still showing the original.

**Comment by FoxUSA** [comment]
In chrome dev tools click disable cache and refresh. Your changes should be reflected like normal as long as dev tools are open.
![image](https://user-images.githubusercontent.com/886680/28449964-0ad4843e-6d99-11e7-9ebe-20f1922a19f3.png)

This is due to OpenNote being an offline HTML5 app. It uses a manifest which tells the browser to cache a bunch of stuff so the site can still work offline. I use it on my phone all the time.
