### ISSUE TITLE
Can't see folder tree view

### ISSUE THREAD

**Issue by mobybit** [FoxUSA/OpenNote#182]
Perhaps it's my fault, but I can't see the tree view. Tags are shown. I tested this with Gnome Web, Icecat and Chromium (both mobile). I used your demo version. Thanks!

**Comment by FoxUSA** [comment]
I removed the folder tree in favor of tags a few versions ago.

If your talking about something else, can you upload a screenshot?

**Comment by mobybit** [comment]
Thanks for your answer!
