### ISSUE TITLE
Does demo on github work?

### ISSUE THREAD

**Issue by sancho-one** [FoxUSA/OpenNote#187]
1. Demo on Github, I click create folder and nothing happens (chrome browser on ubuntu 16.04). 
2. I see no option to add a new note.
3. The same situation on my host. I downloaded and extracted as indicated in instructions.

**Comment by FoxUSA** [comment]
I just checked, it does work. My setup is Chrome 62 on Ubuntu 17.10

**Comment by FoxUSA** [comment]
Good talk
