### ISSUE TITLE
Password Recovery

### ISSUE THREAD

**Issue by rapidpage** [FoxUSA/OpenNote#87]
Is there anyway to recover a password?

**Comment by Snowflake6** [comment]
How can one reset the password by going through MySQL?  I tried deleting the encrypted password that was there, but it doesn't prompt me for a new one.  And if I just put a new one in there (in plaintext), it doesn't accept it when I try logging in.  How do I generate an encrypted PW to put in the MySQL DB?

**Comment by Snowflake6** [comment]
Update - Answering my own question.  At least, for people using phpMySQL, you can select the "ENCRYPT" function when you edit the cell with the password in it.  Enter the password in plaintext, select "ENCRYPT" and hit apply.  The password will be encrypted, and you'll be able to log in with the new password.

**Comment by FoxUSA** [comment]
@Snowflake6,
Password is hashed in PHP. Register a temporary user with the password you want. Then go in MySQL copy the password from the temp and paste it into the user you wanted to change and delete the temp user row.

In new versions we are moving away from doing user management and delegating that to other services which we consume. Like CouchDB

**Comment by Snowflake6** [comment]
That's unfortunate... I may not have the ability to add CouchDB to my website, where I run OpenNote.  Why move away from MySQL?

**Comment by FoxUSA** [comment]
@Snowflake6 
CouchDB lets you do data sync. Remember I keep this up mostly because I use it.

I wanted to be able to have a cached offline app on my phone and have it automatically sync changes back up when I reconnected. I would have to write all that in PHP and MySQL where as I get it for free with CouchDB.

**Comment by Snowflake6** [comment]
Right, I understand.  I like the idea of syncing to the phone, so that's not a bad thing.  Hopefully I can get CouchDB installed on my ISP's server for my domain.  :)

**Comment by FoxUSA** [comment]
@Snowflake6 Run it on you machine. Just sync your phone when connected to wifi.

If you have a home server you can put it on there. Or use AWS with a t2.micro instance. AWS offers a free year.

**Comment by FoxUSA** [comment]
@Snowflake6 a quick google search showed a company that will host a couchdb instance for free
http://www.iriscouch.com/

**Comment by Snowflake6** [comment]
As I already have a domain hosted, i'd prefer to stick with it... I'm very comfortable with the security of my domain right now, and i'd like to stick with it for acccessibility.  I've run a home server before, but the ADSL means retrieving from it takes bloody ages, and the dynamic DNS necessary to keep it running isn't stable enough for my needs.
